name: Check Pull Request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-checks:
    name: Run code checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - name: Run pipeline checks
        run: yarn code:checks

      - name: Build
        run: yarn build